image: gitlab/dind

stages:
  - build-and-push

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

variables:
  GIT_STRATEGY: fetch

build-and-push:
  stage: build-and-push
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN" > ~/.netrc
    - chmod 600 ~/.netrc
    - git clone https://github.com/enanotg/Backend.git
    - cd Backend
    - docker build -t registry.gitlab.com/enanotg/backend .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push registry.gitlab.com/enanotg/backend
  only:
    - main
  tags:
    - docker