name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select Image version to deploy (e.g. 1.0.5):'
        required: false

jobs:
  Deploy-to-AKS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image version
        id: set-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "No version provided, checking latest..."

            LATEST_VERSION=$(gh api -H "Accept: application/vnd.github.v3+json" \
              /orgs/Kevin-Test-K8s/packages/container/backend/versions \
              | jq -r '[.[] | .metadata.container.tags[]?]' \
              | grep -E '^[0-9]+\.[0-9]+$' \
              | sort -V \
              | tail -n 1)

            echo "Using latest version: $LATEST_VERSION"
            echo "VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          else
            echo "Using provided version: ${{ github.event.inputs.version }}"
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        run: |
          az aks get-credentials --resource-group k8s-terraform --name k8s-terraform-cluster
          kubectl get nodes

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/backend -n default

      - name: Update Image in Deployment
        run: |
          kubectl set image deployment/backend backend=ghcr.io/kevin-test-k8s/backend:$VERSION -n default
          kubectl rollout status deployment/backend -n default

      - name: Verify Deployment
        run: |
          echo "Verifying Pods Status..."
          kubectl get pods -n default
          echo "Verifying Logs..."
          kubectl logs -l app=backend -n default || true
